In [99]:
import nba_py
from nba_py import player
from nba_py import constants
import requests
import json
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup

In [100]:
years=np.arange(1985,2019)
tabledat=[]

for year in years:
    path='https://www.basketball-reference.com/leagues/NBA_'+str(year)+'_advanced.html'
    soup=BeautifulSoup(requests.get(path).text,'html.parser')
    tab=soup.find('table')
    if year==1985:
        headers=tab.find_all('th')
        #header=headers[0].text.strip()
        headers=[header.text.strip() for header in headers]
        headers=headers[1:29]
        headers=[header for header in headers if len(header)>0]
        headers.append('Year')
        print(headers)

    rows=tab.find_all('tr')
    for row in rows:
        cols=row.find_all('td')
        cols=[ele.text.strip() for ele in cols]
        rowdat=[ele for ele in cols if ele]
        if len(rowdat)>0:
            rowdat.append(year)
            tabledat.append(rowdat)
    
advdat=pd.DataFrame(tabledat,columns=headers)

['Player', 'Pos', 'Age', 'Tm', 'G', 'MP', 'PER', 'TS%', '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%', 'USG%', 'OWS', 'DWS', 'WS', 'WS/48', 'OBPM', 'DBPM', 'BPM', 'VORP', 'Year']

In [101]:
advdat.head()

,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,FTr,...,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Year
0,Kareem Abdul-Jabbar*,C,37,LAL,79,2630,22.9,.628,.001,.327,...,24.3,7.6,3.6,11.2,.204,3.6,1.3,4.9,4.6,1985.0
1,Alvan Adams,PF,30,PHO,82,2136,19.8,.578,.000,.309,...,23.6,3.5,3.3,6.8,.152,2.3,2.1,4.4,3.5,1985.0
2,Mark Aguirre,SF,25,DAL,80,2699,21.3,.563,.054,.370,...,32.2,5.3,1.9,7.2,.128,3.6,-1.9,1.7,2.5,1985.0
3,Danny Ainge,SG,25,BOS,75,2564,14.2,.570,.071,.172,...,15.9,3.9,2.8,6.6,.124,1.3,0.4,1.7,2.4,1985.0
4,Chuck Aleksinas,C,25,GSW,74,1114,9.1,.509,.003,.223,...,15.6,0.1,0.4,0.4,.019,-3.9,-2.0,-5.9,-1.1,1985.0

In [102]:
print(advdat.shape)
#advdat['WS']=pd.to_numeric(advdat['WS'])

advdat.iloc[:,4:]=advdat.iloc[:,4:].apply(pd.to_numeric)
advdat.iloc[:,2]=advdat.iloc[:,2].apply(pd.to_numeric)
advdat.dtypes
#advdat.sort_values('DWS',ascending=False)

(17764, 27)

Player     object
Pos        object
Age         int64
Tm         object
G           int64
MP          int64
PER       float64
TS%       float64
3PAr      float64
FTr       float64
ORB%      float64
DRB%      float64
TRB%      float64
AST%      float64
STL%      float64
BLK%      float64
TOV%      float64
USG%      float64
OWS       float64
DWS       float64
WS        float64
WS/48     float64
OBPM      float64
DBPM      float64
BPM       float64
VORP      float64
Year      float64
dtype: object

In [103]:
# multip=advdat.groupby(['Player','year'],as_index=False).agg({'Tm':'count'})
# advdat=advat.merge(multip,on=['Player','year']).rename({'Tm_x':'Tm','Tm_y':'Tms'},axis='columns')
# multip=multip[multip.Tm>1]
# multip=multip.merge(advdat,on=['Player','year']).drop(columns='Tm_x').rename({'Tm_y':'Tm'},axis='columns')
#advdat=advdat.groupby(['Player','year'],as_index=False).apply(lambda x:x.sort_values('G',ascending=False).iloc[0])
#advdat.loc[advdat.Tm=='TOT','Tm']='MULTI'
#.reset_index().first(1)#.Tm_y.transform(lambda x:'-'.join(x))
#multip.sort_values(['year','Player','G'],ascending=[True,True,False]).groupby(['Player','year'],as_index=False).Tm.transform(lambda x:'-'.join(x))
#multip

In [104]:
advdat.Player=advdat.Player.str.replace('*','')

In [105]:
advdat.head()

,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,FTr,...,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Year
0,Kareem Abdul-Jabbar,C,37,LAL,79,2630,22.9,0.628,0.001,0.327,...,24.3,7.6,3.6,11.2,0.204,3.6,1.3,4.9,4.6,1985.0
1,Alvan Adams,PF,30,PHO,82,2136,19.8,0.578,0.000,0.309,...,23.6,3.5,3.3,6.8,0.152,2.3,2.1,4.4,3.5,1985.0
2,Mark Aguirre,SF,25,DAL,80,2699,21.3,0.563,0.054,0.370,...,32.2,5.3,1.9,7.2,0.128,3.6,-1.9,1.7,2.5,1985.0
3,Danny Ainge,SG,25,BOS,75,2564,14.2,0.570,0.071,0.172,...,15.9,3.9,2.8,6.6,0.124,1.3,0.4,1.7,2.4,1985.0
4,Chuck Aleksinas,C,25,GSW,74,1114,9.1,0.509,0.003,0.223,...,15.6,0.1,0.4,0.4,0.019,-3.9,-2.0,-5.9,-1.1,1985.0

In [111]:
drafttab=[]
offset=0
path='https://www.basketball-reference.com/play-index/draft_finder.cgi?request=1&year_min=1985&year_max=&round_min=1&round_max=1&pick_overall_min=&pick_overall_max=&franch_id=&college_id=0&is_active=&is_hof=&pos_is_g=Y&pos_is_gf=Y&pos_is_f=Y&pos_is_fg=Y&pos_is_fc=Y&pos_is_c=Y&pos_is_cf=Y&c1stat=&c1comp=&c1val=&c2stat=&c2comp=&c2val=&c3stat=&c3comp=&c3val=&c4stat=&c4comp=&c4val=&order_by=year_id&order_by_asc=&offset='+str(offset)
soup=BeautifulSoup(requests.get(path).text,'html.parser')
tab=soup.find('table')
draftheaders=tab.find_all('th')
#header=headers[0].text.strip()
draftheaders=[header.text.strip() for header in draftheaders]

while tab!=None:
#for i in range(5):
    rows=tab.find_all('tr')
    for row in rows:
        cols=row.find_all('td')
        cols=[ele.text.strip() for ele in cols]
        rowdat=[ele for ele in cols]
        if len(rowdat)>0:
            #rowdat.append(year)
            drafttab.append(rowdat)
    offset+=100
    path='https://www.basketball-reference.com/play-index/draft_finder.cgi?request=1&year_min=1985&year_max=&round_min=1&round_max=1&pick_overall_min=&pick_overall_max=&franch_id=&college_id=0&is_active=&is_hof=&pos_is_g=Y&pos_is_gf=Y&pos_is_f=Y&pos_is_fg=Y&pos_is_fc=Y&pos_is_c=Y&pos_is_cf=Y&c1stat=&c1comp=&c1val=&c2stat=&c2comp=&c2val=&c3stat=&c3comp=&c3val=&c4stat=&c4comp=&c4val=&order_by=year_id&order_by_asc=&offset='+str(offset)
    soup=BeautifulSoup(requests.get(path).text,'html.parser')
    tab=soup.find('table')
 
lotdat=pd.DataFrame(drafttab,columns=draftheaders[6:31])

In [112]:
lotdat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 935 entries, 0 to 934
Data columns (total 25 columns):
Year       935 non-null object
Lg         935 non-null object
Rd         935 non-null object
Pk         935 non-null object
Tm         935 non-null object
Player     935 non-null object
Age        935 non-null object
Pos        935 non-null object
Born       935 non-null object
College    935 non-null object
From       935 non-null object
To         935 non-null object
G          935 non-null object
MP         935 non-null object
PTS        935 non-null object
TRB        935 non-null object
AST        935 non-null object
STL        935 non-null object
BLK        935 non-null object
FG%        935 non-null object
2P%        935 non-null object
3P%        935 non-null object
FT%        935 non-null object
WS         935 non-null object
WS/48      935 non-null object
dtypes: object(25)
memory usage: 182.7+ KB

In [113]:
lotdat.drop(inplace=True,columns='Lg')
lotdat.iloc[:,:2]=lotdat.iloc[:,:2].apply(pd.to_numeric)
lotdat.iloc[:,5]=lotdat.iloc[:,5].apply(pd.to_numeric)
lotdat.iloc[:,9:]=lotdat.iloc[:,9:].apply(pd.to_numeric)
#advdat.iloc[:,4:]=advdat.iloc[:,:].apply(pd.to_numeric)

In [114]:
lotdat[lotdat.Player.str.contains('LeBron')]

,Year,Rd,Pk,Tm,Player,Age,Pos,Born,College,From,...,TRB,AST,STL,BLK,FG%,2P%,3P%,FT%,WS,WS/48
419,2003,1,1,CLE,LeBron James,18.182,F-G,us,,2004.0,...,7.4,7.2,1.6,0.8,0.504,0.547,0.344,0.739,219.4,0.238

In [123]:
lotdat['mergename']=lotdat.Player
lotdat.mergename=lotdat.mergename.str.replace('*','')
lotdat.mergename=lotdat.mergename.replace('Waller-','')
lotdat.mergename=lotdat.mergename.str.replace('-','')
lotdat.mergename=lotdat.mergename.str.replace("'",'')
lotdat.mergename=lotdat.mergename.str.replace(' Jr.','')
lotdat.mergename=lotdat.mergename.str.replace(' III','')
lotdat.mergename=lotdat.mergename.str.replace(' ','')
lotdat.mergename=lotdat.mergename.str.replace('.','')
lotdat.mergename=lotdat.mergename.str.lower()
lotdat.mergename=lotdat.mergename.str.replace('patrickmills','pattymills')

advdat['mergename']=advdat.Player
advdat.mergename=advdat.mergename.str.replace('*','')
advdat.mergename=advdat.mergename.str.replace('Waller-','')
advdat.mergename=advdat.mergename.str.replace('-','')
advdat.mergename=advdat.mergename.str.replace("'",'')
advdat.mergename=advdat.mergename.str.replace(" Jr.",'')
advdat.mergename=advdat.mergename.str.replace(" III",'')
advdat.mergename=advdat.mergename.str.replace(" ",'')
advdat.mergename=advdat.mergename.str.replace(".",'')
advdat.mergename=advdat.mergename.str.lower()
advdat.mergename=advdat.mergename.str.replace("cabarrot",'')

In [124]:

lotadv=lotdat.merge(advdat,how='left',on=['mergename'],suffixes=['_draft','_season'],copy=False)

In [125]:
lotadv

,Year_draft,Rd,Pk,Tm_draft,Player_draft,Age_draft,Pos_draft,Born,College,From,...,USG%,OWS,DWS,WS_season,WS/48_season,OBPM,DBPM,BPM,VORP,Year_season
0,2017,1,1,PHI,Markelle Fultz,19.029,G,us,University of Washington,2018.0,...,23.100,-0.2,0.4,0.2,0.043,-3.8,0.8,-3.0,-0.1,2018.0
1,2017,1,2,LAL,Lonzo Ball,19.243,G,us,"University of California, Los Angeles",2018.0,...,17.400,-0.5,2.5,2.0,0.053,-0.8,2.5,1.7,1.7,2018.0
2,2017,1,3,BOS,Jayson Tatum,19.116,F,us,Duke University,2018.0,...,19.500,3.0,4.0,7.1,0.139,-0.5,1.5,1.0,1.8,2018.0
3,2017,1,4,PHO,Josh Jackson,20.137,F-G,us,University of Kansas,2018.0,...,26.000,-2.0,1.2,-0.7,-0.018,-3.1,-1.2,-4.3,-1.1,2018.0
4,2017,1,5,SAC,De'Aaron Fox,19.189,G,us,University of Kentucky,2018.0,...,23.400,-1.7,1.1,-0.6,-0.014,-2.8,-1.5,-4.4,-1.2,2018.0
5,2017,1,6,ORL,Jonathan Isaac,19.267,F,us,Florida State University,2018.0,...,15.000,-0.6,0.8,0.2,0.021,-4.9,3.1,-1.8,0.0,2018.0
6,2017,1,7,MIN,Lauri Markkanen,20.036,F-C,fi,University of Arizona,2018.0,...,21.900,1.7,1.6,3.3,0.079,-0.6,-1.3,-1.9,0.1,2018.0
7,2017,1,8,NYK,Frank Ntilikina,18.334,G,be,,2018.0,...,16.900,-2.0,1.1,-0.9,-0.026,-3.5,-0.5,-3.9,-0.8,2018.0
8,2017,1,9,DAL,Dennis Smith,19.214,G,us,North Carolina State University,2018.0,...,28.900,-2.4,1.7,-0.7,-0.017,-1.5,-0.7,-2.3,-0.1,2018.0
9,2017,1,10,SAC,Zach Collins,19.220,C-F,us,Gonzaga University,2018.0,...,15.400,-0.7,1.3,0.6,0.030,-4.1,0.9,-3.2,-0.3,2018.0
10,2017,1,11,CHO,Malik Monk,19.143,G,us,University of Kentucky,2018.0,...,24.900,-0.5,0.5,0.0,0.001,-1.0,-3.4,-4.4,-0.5,2018.0
11,2017,1,12,DET,Luke Kennard,21.003,G,us,Duke University,2018.0,...,17.200,1.1,1.4,2.6,0.085,-1.1,-0.4,-1.5,0.2,2018.0
12,2017,1,13,DEN,Donovan Mitchell,20.293,G,us,University of Louisville,2018.0,...,29.100,1.4,3.8,5.2,0.095,1.3,-0.2,1.1,2.1,2018.0
13,2017,1,14,MIA,Bam Adebayo,19.344,C-F,us,University of Kentucky,2018.0,...,15.900,2.3,1.9,4.2,0.148,-1.6,1.8,0.2,0.8,2018.0
14,2017,1,15,POR,Justin Jackson,22.092,G-F,us,University of North Carolina,2018.0,...,14.200,0.4,0.5,1.0,0.031,-2.0,-1.5,-3.5,-0.6,2018.0
15,2017,1,16,CHI,Justin Patton,20.013,C,us,Creighton University,2018.0,...,22.100,0.0,0.0,0.0,0.151,-0.7,4.0,3.3,0.0,2018.0
16,2017,1,17,MIL,D.J. Wilson,21.129,F,us,University of Michigan,2018.0,...,13.300,0.0,0.1,0.1,0.054,-2.9,-1.2,-4.1,0.0,2018.0
17,2017,1,18,IND,T.J. Leaf,20.058,F,il,"University of California, Los Angeles",2018.0,...,14.900,0.5,0.3,0.8,0.082,-1.9,-2.9,-4.8,-0.3,2018.0
18,2017,1,19,ATL,John Collins,19.277,F,us,Wake Forest University,2018.0,...,17.900,3.4,2.0,5.4,0.145,-0.2,1.9,1.7,1.7,2018.0
19,2017,1,20,POR,Harry Giles,19.066,F-C,us,Duke University,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2017,1,21,OKC,Terrance Ferguson,19.041,G-F,us,,2018.0,...,10.400,0.7,0.5,1.2,0.077,-1.2,-1.3,-2.5,-0.1,2018.0
21,2017,1,22,BRK,Jarrett Allen,19.067,F-C,us,University of Texas at Austin,2018.0,...,16.300,2.7,1.5,4.2,0.141,-1.3,1.4,0.2,0.8,2018.0
22,2017,1,23,TOR,OG Anunoby,19.345,F,gb,Indiana University,2018.0,...,12.400,1.4,1.6,3.0,0.098,0.2,0.4,0.6,1.0,2018.0
23,2017,1,24,UTA,Tyler Lydon,21.079,F,us,Syracuse University,2018.0,...,-0.014,-5.7,-0.8,-6.5,0.000,2018.0,NaN,NaN,NaN,NaN
24,2017,1,25,ORL,Anzejs Pasecniks,21.190,C,lv,,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2017,1,26,POR,Caleb Swanigan,20.070,F,us,Purdue University,2018.0,...,20.000,-0.3,0.3,0.0,-0.003,-6.0,0.6,-5.4,-0.2,2018.0
26,2017,1,27,BRK,Kyle Kuzma,21.339,F,us,University of Utah,2018.0,...,22.500,1.5,2.3,3.8,0.077,-0.3,-1.0,-1.3,0.4,2018.0
27,2017,1,28,LAL,Tony Bradley,19.170,F-C,us,University of North Carolina,2018.0,...,18.400,0.0,0.0,0.0,0.033,-6.6,-3.0,-9.6,-0.1,2018.0
28,2017,1,29,SAS,Derrick White,22.361,G,us,University of Colorado,2018.0,...,15.400,0.3,0.2,0.5,0.170,0.0,0.5,0.5,0.1,2018.0
29,2017,1,30,UTA,Josh Hart,22.114,G,us,Villanova University,2018.0,...,13.500,1.9,1.5,3.4,0.111,-0.3,0.2,-0.1,0.7,2018.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8793,1985,1,23,LAL,A.C. Green,21.263,F-C,us,Oregon State University,1986.0,...,15.600,3.2,2.9,6.1,0.135,0.0,0.6,0.5,1.4,1991.0
8794,1985,1,23,LAL,A.C. Green,21.263,F-C,us,Oregon State University,1986.0,...,16.800,5.8,2.9,8.8,0.145,1.2,0.2,1.4,2.5,1992.0
8795,1985,1,23,LAL,A.C. Green,21.263,F-C,us,Oregon State University,1986.0,...,15.000,6.1,2.6,8.6,0.147,1.6,0.5,2.0,2.9,1993.0
8796,1985,1,23,LAL,A.C. Green,21.263,F-C,us,Oregon State University,1986.0,...,17.600,6.7,2.6,9.3,0.157,1.5,-0.3,1.2,2.3,1994.0
8797,1985,1,23,LAL,A.C. Green,21.263,F-C,us,Oregon State University,1986.0,...,14.200,4.6,2.1,6.7,0.120,0.6,0.2,0.7,1.9,1995.0
8798,1985,1,23,LAL,A.C. Green,21.263,F-C,us,Oregon State University,1986.0,...,13.200,2.7,1.7,4.4,0.100,-1.1,-0.3,-1.4,0.3,1996.0
8799,1985,1,23,LAL,A.C. Green,21.263,F-C,us,Oregon State University,1986.0,...,11.800,2.4,2.4,4.8,0.093,-1.8,0.7,-1.1,0.6,1997.0
8800,1985,1,23,LAL,A.C. Green,21.263,F-C,us,Oregon State University,1986.0,...,13.900,0.3,0.5,0.8,0.073,-3.1,-0.2,-3.3,-0.2,1997.0
8801,1985,1,23,LAL,A.C. Green,21.263,F-C,us,Oregon State University,1986.0,...,11.200,2.2,1.8,4.0,0.099,-1.4,0.9,-0.5,0.7,1997.0
8802,1985,1,23,LAL,A.C. Green,21.263,F-C,us,Oregon State University,1986.0,...,11.600,2.8,2.4,5.2,0.095,-1.7,1.0,-0.7,0.9,1998.0
8803,1985,1,23,LAL,A.C. Green,21.263,F-C,us,Oregon State University,1986.0,...,14.800,0.7,0.7,1.4,0.074,-1.9,-0.9,-2.8,-0.2,1999.0
8804,1985,1,23,LAL,A.C. Green,21.263,F-C,us,Oregon State University,1986.0,...,11.000,1.7,3.3,5.0,0.124,-2.0,1.8,-0.2,0.9,2000.0
8805,1985,1,23,LAL,A.C. Green,21.263,F-C,us,Oregon State University,1986.0,...,14.400,1.1,2.1,3.2,0.110,-3.2,0.2,-3.0,-0.3,2001.0
8806,1985,1,24,POR,Terry Porter,22.077,G,us,University of Wisconsin-Stevens Point,1986.0,...,20.200,1.2,1.1,2.3,0.093,-0.1,-1.0,-1.1,0.3,1986.0
8807,1985,1,24,POR,Terry Porter,22.077,G,us,University of Wisconsin-Stevens Point,1986.0,...,17.000,4.0,2.8,6.8,0.120,1.1,0.2,1.3,2.2,1987.0
8808,1985,1,24,POR,Terry Porter,22.077,G,us,University of Wisconsin-Stevens Point,1986.0,...,16.800,6.5,3.3,9.8,0.157,2.4,0.0,2.4,3.4,1988.0
8809,1985,1,24,POR,Terry Porter,22.077,G,us,University of Wisconsin-Stevens Point,1986.0,...,19.100,6.5,2.6,9.2,0.142,2.8,-0.6,2.2,3.3,1989.0
8810,1985,1,24,POR,Terry Porter,22.077,G,us,University of Wisconsin-Stevens Point,1986.0,...,20.100,7.9,3.8,11.7,0.202,4.4,0.0,4.3,4.4,1990.0
8811,1985,1,24,POR,Terry Porter,22.077,G,us,University of Wisconsin-Stevens Point,1986.0,...,19.600,9.2,3.9,13.0,0.235,5.9,0.3,6.1,5.5,1991.0
8812,1985,1,24,POR,Terry Porter,22.077,G,us,University of Wisconsin-Stevens Point,1986.0,...,21.600,7.0,3.5,10.6,0.182,3.6,-0.5,3.1,3.6,1992.0
8813,1985,1,24,POR,Terry Porter,22.077,G,us,University of Wisconsin-Stevens Point,1986.0,...,21.100,5.7,3.1,8.8,0.147,2.9,-0.5,2.4,3.2,1993.0
8814,1985,1,24,POR,Terry Porter,22.077,G,us,University of Wisconsin-Stevens Point,1986.0,...,21.700,3.5,1.8,5.4,0.124,2.4,-1.3,1.0,1.6,1994.0
8815,1985,1,24,POR,Terry Porter,22.077,G,us,University of Wisconsin-Stevens Point,1986.0,...,19.800,0.9,0.8,1.7,0.106,0.6,-1.0,-0.4,0.3,1995.0
8816,1985,1,24,POR,Terry Porter,22.077,G,us,University of Wisconsin-Stevens Point,1986.0,...,18.700,2.3,1.3,3.7,0.085,1.2,-2.0,-0.8,0.6,1996.0
8817,1985,1,24,POR,Terry Porter,22.077,G,us,University of Wisconsin-Stevens Point,1986.0,...,19.000,1.5,1.2,2.7,0.082,0.3,-2.1,-1.8,0.1,1997.0
8818,1985,1,24,POR,Terry Porter,22.077,G,us,University of Wisconsin-Stevens Point,1986.0,...,19.100,4.3,0.9,5.2,0.139,2.9,-2.2,0.7,1.2,1998.0
8819,1985,1,24,POR,Terry Porter,22.077,G,us,University of Wisconsin-Stevens Point,1986.0,...,18.400,3.3,1.7,5.0,0.178,2.8,0.0,2.8,1.7,1999.0
8820,1985,1,24,POR,Terry Porter,22.077,G,us,University of Wisconsin-Stevens Point,1986.0,...,18.300,3.4,2.3,5.6,0.168,2.7,0.0,2.7,1.9,2000.0
8821,1985,1,24,POR,Terry Porter,22.077,G,us,University of Wisconsin-Stevens Point,1986.0,...,16.700,3.0,2.3,5.4,0.154,2.0,0.2,2.2,1.8,2001.0
8822,1985,1,24,POR,Terry Porter,22.077,G,us,University of Wisconsin-Stevens Point,1986.0,...,15.900,1.6,1.9,3.5,0.131,0.2,0.6,0.8,0.9,2002.0

In [126]:
lotadv.shape

(8823, 52)

In [127]:
lotdat.shape

(935, 25)

In [128]:
advdat.shape

(17764, 28)

In [129]:
lotadv.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8823 entries, 0 to 8822
Data columns (total 52 columns):
Year_draft       8823 non-null object
Rd               8823 non-null object
Pk               8823 non-null object
Tm_draft         8823 non-null object
Player_draft     8823 non-null object
Age_draft        8819 non-null float64
Pos_draft        8823 non-null object
Born             8823 non-null object
College          8823 non-null object
From             8813 non-null float64
To               8813 non-null float64
G_draft          8813 non-null float64
MP_draft         8813 non-null float64
PTS              8813 non-null float64
TRB              8813 non-null float64
AST              8813 non-null float64
STL              8813 non-null float64
BLK              8813 non-null float64
FG%              8812 non-null float64
2P%              8812 non-null float64
3P%              8683 non-null float64
FT%              8809 non-null float64
WS_draft         8813 non-null float64
WS/48_draft      8813 non-null float64
mergename        8823 non-null object
Player_season    8813 non-null object
Pos_season       8813 non-null object
Age_season       8813 non-null float64
Tm_season        8813 non-null object
G_season         8813 non-null float64
MP_season        8813 non-null float64
PER              8813 non-null float64
TS%              8813 non-null float64
3PAr             8813 non-null float64
FTr              8813 non-null float64
ORB%             8813 non-null float64
DRB%             8813 non-null float64
TRB%             8813 non-null float64
AST%             8813 non-null float64
STL%             8812 non-null float64
BLK%             8812 non-null float64
TOV%             8812 non-null float64
USG%             8812 non-null float64
OWS              8812 non-null float64
DWS              8812 non-null float64
WS_season        8812 non-null float64
WS/48_season     8812 non-null float64
OBPM             8812 non-null float64
DBPM             8803 non-null float64
BPM              8801 non-null float64
VORP             8799 non-null float64
Year_season      8799 non-null float64
dtypes: float64(40), object(12)
memory usage: 3.6+ MB

In [130]:
lotadv.columns

Index(['Year_draft', 'Rd', 'Pk', 'Tm_draft', 'Player_draft', 'Age_draft',
       'Pos_draft', 'Born', 'College', 'From', 'To', 'G_draft', 'MP_draft',
       'PTS', 'TRB', 'AST', 'STL', 'BLK', 'FG%', '2P%', '3P%', 'FT%',
       'WS_draft', 'WS/48_draft', 'mergename', 'Player_season', 'Pos_season',
       'Age_season', 'Tm_season', 'G_season', 'MP_season', 'PER', 'TS%',
       '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%',
       'USG%', 'OWS', 'DWS', 'WS_season', 'WS/48_season', 'OBPM', 'DBPM',
       'BPM', 'VORP', 'Year_season'],
      dtype='object')

In [141]:
print(lotadv[lotadv['WS_season'].isnull()].shape)
print(lotadv[(lotadv['WS_season'].isnull())&(lotadv['Rd']==1)][['Year_draft','mergename','Player_draft','Rd','Pk']])

(11, 52)
     Year_draft         mergename        Player_draft Rd  Pk
19         2017        harrygiles         Harry Giles  1  20
24         2017   anzejspasecniks    Anzejs Pasecniks  1  25
180        2015   nikolamilutinov    Nikola Milutinov  1  26
493        2013  liviojeancharles  Livio Jean-Charles  1  28
1085       2010       damionjames        Damion James  1  24
2008       2007    petterikoponen     Petteri Koponen  1  30
2412       2005       franvazquez        Fran Vazquez  1  11
4375       1999      fredericweis       Frederic Weis  1  15
7160       1991     shaunvandiver      Shaun Vandiver  1  25
8353       1986           lenbias            Len Bias  1   2
8512       1986         kenbarlow          Ken Barlow  1  23

In [134]:
lotadv.iloc[19,]

Year_draft                  2017
Rd                             1
Pk                            20
Tm_draft                     POR
Player_draft         Harry Giles
Age_draft                 19.066
Pos_draft                    F-C
Born                          us
College          Duke University
From                         NaN
To                           NaN
G_draft                      NaN
MP_draft                     NaN
PTS                          NaN
TRB                          NaN
AST                          NaN
STL                          NaN
BLK                          NaN
FG%                          NaN
2P%                          NaN
3P%                          NaN
FT%                          NaN
WS_draft                     NaN
WS/48_draft                  NaN
mergename             harrygiles
Player_season                NaN
Pos_season                   NaN
Age_season                   NaN
Tm_season                    NaN
G_season                     NaN
MP_season                    NaN
PER                          NaN
TS%                          NaN
3PAr                         NaN
FTr                          NaN
ORB%                         NaN
DRB%                         NaN
TRB%                         NaN
AST%                         NaN
STL%                         NaN
BLK%                         NaN
TOV%                         NaN
USG%                         NaN
OWS                          NaN
DWS                          NaN
WS_season                    NaN
WS/48_season                 NaN
OBPM                         NaN
DBPM                         NaN
BPM                          NaN
VORP                         NaN
Year_season                  NaN
Name: 19, dtype: object

In [176]:
lotadv['projage']=lotadv['Age_draft']+(lotadv['Year_season']-lotadv['Year_draft'])
lotadv['agecheck']=abs(lotadv['projage']-lotadv['Age_season'])

In [177]:
lotadv[((lotadv.Year_season>lotadv.To)|(lotadv.Year_season<lotadv.From))&(lotadv.agecheck<2)][['Year_draft','Player_draft','Year_season','projage','Age_season','agecheck']]

Empty DataFrame
Columns: [Year_draft, Player_draft, Year_season, projage, Age_season, agecheck]
Index: []

In [182]:
lotadv=lotadv[(lotadv.Year_season<=lotadv.To)&(lotadv.Year_season>=lotadv.From)]
lotadv[lotadv.agecheck>1.1][['Year_draft','Player_draft','Tm_season','Year_season','projage','Age_season','agecheck']]

,Year_draft,Player_draft,Tm_season,Year_season,projage,Age_season,agecheck
2,2017,Jayson Tatum,BOS,2018.0,20.116,19.0,1.116
3,2017,Josh Jackson,PHO,2018.0,21.137,20.0,1.137
10,2017,Malik Monk,CHO,2018.0,20.143,19.0,1.143
16,2017,D.J. Wilson,MIL,2018.0,22.129,21.0,1.129
29,2017,Josh Hart,LAL,2018.0,23.114,22.0,1.114
37,2016,Kris Dunn,MIN,2017.0,23.103,22.0,1.103
38,2016,Kris Dunn,CHI,2018.0,24.103,23.0,1.103
43,2016,Jamal Murray,DEN,2017.0,20.125,19.0,1.125
44,2016,Jamal Murray,DEN,2018.0,21.125,20.0,1.125
49,2016,Thon Maker,MIL,2017.0,20.123,19.0,1.123
50,2016,Thon Maker,MIL,2018.0,21.123,20.0,1.123
86,2016,Pascal Siakam,TOR,2017.0,23.145,22.0,1.145
87,2016,Pascal Siakam,TOR,2018.0,24.145,23.0,1.145
88,2016,Skal Labissiere,SAC,2017.0,21.102,20.0,1.102
89,2016,Skal Labissiere,SAC,2018.0,22.102,21.0,1.102
97,2015,D'Angelo Russell,LAL,2016.0,20.127,19.0,1.127
98,2015,D'Angelo Russell,LAL,2017.0,21.127,20.0,1.127
99,2015,D'Angelo Russell,BRK,2018.0,22.127,21.0,1.127
108,2015,Mario Hezonja,ORL,2016.0,21.125,20.0,1.125
109,2015,Mario Hezonja,ORL,2017.0,22.125,21.0,1.125
110,2015,Mario Hezonja,ORL,2018.0,23.125,22.0,1.125
114,2015,Emmanuel Mudiay,DEN,2016.0,20.116,19.0,1.116
115,2015,Emmanuel Mudiay,DEN,2017.0,21.116,20.0,1.116
116,2015,Emmanuel Mudiay,TOT,2018.0,22.116,21.0,1.116
117,2015,Emmanuel Mudiay,DEN,2018.0,22.116,21.0,1.116
118,2015,Emmanuel Mudiay,NYK,2018.0,22.116,21.0,1.116
145,2015,Terry Rozier,BOS,2016.0,22.105,21.0,1.105
146,2015,Terry Rozier,BOS,2017.0,23.105,22.0,1.105
147,2015,Terry Rozier,BOS,2018.0,24.105,23.0,1.105
168,2015,Bobby Portis,CHI,2016.0,21.14,20.0,1.14
...,...,...,...,...,...,...,...
8153,1987,Kenny Smith,HOU,1995.0,30.111,29.0,1.111
8154,1987,Kenny Smith,HOU,1996.0,31.111,30.0,1.111
8155,1987,Kenny Smith,TOT,1997.0,32.111,31.0,1.111
8156,1987,Kenny Smith,DET,1997.0,32.111,31.0,1.111
8157,1987,Kenny Smith,ORL,1997.0,32.111,31.0,1.111
8158,1987,Kenny Smith,DEN,1997.0,32.111,31.0,1.111
8159,1987,Kevin Johnson,TOT,1988.0,22.115,21.0,1.115
8160,1987,Kevin Johnson,CLE,1988.0,22.115,21.0,1.115
8161,1987,Kevin Johnson,PHO,1988.0,22.115,21.0,1.115
8162,1987,Kevin Johnson,PHO,1989.0,23.115,22.0,1.115
8163,1987,Kevin Johnson,PHO,1990.0,24.115,23.0,1.115
8164,1987,Kevin Johnson,PHO,1991.0,25.115,24.0,1.115
8165,1987,Kevin Johnson,PHO,1992.0,26.115,25.0,1.115
8166,1987,Kevin Johnson,PHO,1993.0,27.115,26.0,1.115
8167,1987,Kevin Johnson,PHO,1994.0,28.115,27.0,1.115
8168,1987,Kevin Johnson,PHO,1995.0,29.115,28.0,1.115
8169,1987,Kevin Johnson,PHO,1996.0,30.115,29.0,1.115
8170,1987,Kevin Johnson,PHO,1997.0,31.115,30.0,1.115
8171,1987,Kevin Johnson,PHO,1998.0,32.115,31.0,1.115
8172,1987,Kevin Johnson,PHO,2000.0,34.115,33.0,1.115
8502,1986,Scott Skiles,MIL,1987.0,23.109,22.0,1.109
8503,1986,Scott Skiles,IND,1988.0,24.109,23.0,1.109
8504,1986,Scott Skiles,IND,1989.0,25.109,24.0,1.109
8505,1986,Scott Skiles,ORL,1990.0,26.109,25.0,1.109
8506,1986,Scott Skiles,ORL,1991.0,27.109,26.0,1.109
8507,1986,Scott Skiles,ORL,1992.0,28.109,27.0,1.109
8508,1986,Scott Skiles,ORL,1993.0,29.109,28.0,1.109
8509,1986,Scott Skiles,ORL,1994.0,30.109,29.0,1.109
8510,1986,Scott Skiles,WSB,1995.0,31.109,30.0,1.109
8511,1986,Scott Skiles,PHI,1996.0,32.109,31.0,1.109

In [171]:
lotadv[lotadv.Player_draft=='Charles Smith'][['Year_draft','Player_draft','Tm_season','Year_season','projage','Age_season','agecheck']]

,Year_draft,Player_draft,Tm_season,Year_season,projage,Age_season,agecheck
5190,1997,Charles Smith,TOT,1998.0,22,22.0,0
5191,1997,Charles Smith,MIA,1998.0,22,22.0,0
5192,1997,Charles Smith,LAC,1998.0,22,22.0,0
5193,1997,Charles Smith,LAC,1999.0,23,23.0,0
5194,1997,Charles Smith,SAS,2002.0,26,26.0,0
5195,1997,Charles Smith,POR,2003.0,27,27.0,0
5196,1997,Charles Smith,TOT,2006.0,30,30.0,0
5197,1997,Charles Smith,POR,2006.0,30,30.0,0
5198,1997,Charles Smith,DEN,2006.0,30,30.0,0
7786,1988,Charles Smith,LAC,1989.0,23,23.0,0
7787,1988,Charles Smith,LAC,1990.0,24,24.0,0
7788,1988,Charles Smith,BOS,1990.0,24,22.0,2
7789,1988,Charles Smith,LAC,1991.0,25,25.0,0
7790,1988,Charles Smith,BOS,1991.0,25,23.0,2
7791,1988,Charles Smith,LAC,1992.0,26,26.0,0
7792,1988,Charles Smith,NYK,1993.0,27,27.0,0
7793,1988,Charles Smith,NYK,1994.0,28,28.0,0
7794,1988,Charles Smith,NYK,1995.0,29,29.0,0
7795,1988,Charles Smith,MIN,1996.0,30,28.0,2
7796,1988,Charles Smith,TOT,1996.0,30,30.0,0
7797,1988,Charles Smith,NYK,1996.0,30,30.0,0
7798,1988,Charles Smith,SAS,1996.0,30,30.0,0
7799,1988,Charles Smith,SAS,1997.0,31,31.0,0

In [186]:
lotadv=lotadv[lotadv.agecheck<1.2]
lotadv=lotadv[lotadv.Tm_season!='TOT']
lotadv.shape

(7970, 54)

In [193]:
lotadv['sincedrafted']=lotadv['Year_season']-lotadv['Year_draft']
lotadv.head()

,Year_draft,Rd,Pk,Tm_draft,Player_draft,Age_draft,Pos_draft,Born,College,From,...,WS_season,WS/48_season,OBPM,DBPM,BPM,VORP,Year_season,projage,agecheck,sincedrafted
0,2017,1,1,PHI,Markelle Fultz,19.029,G,us,University of Washington,2018.0,...,0.2,0.043,-3.8,0.8,-3.0,-0.1,2018.0,20.029,1.029,1
1,2017,1,2,LAL,Lonzo Ball,19.243,G,us,"University of California, Los Angeles",2018.0,...,2.0,0.053,-0.8,2.5,1.7,1.7,2018.0,20.243,0.243,1
2,2017,1,3,BOS,Jayson Tatum,19.116,F,us,Duke University,2018.0,...,7.1,0.139,-0.5,1.5,1.0,1.8,2018.0,20.116,1.116,1
3,2017,1,4,PHO,Josh Jackson,20.137,F-G,us,University of Kansas,2018.0,...,-0.7,-0.018,-3.1,-1.2,-4.3,-1.1,2018.0,21.137,1.137,1
4,2017,1,5,SAC,De'Aaron Fox,19.189,G,us,University of Kentucky,2018.0,...,-0.6,-0.014,-2.8,-1.5,-4.4,-1.2,2018.0,20.189,0.189,1

In [195]:
lotadv=lotadv[lotadv.sincedrafted<=5]
lotadv.to_csv('lot_adv.csv')

NBA API <<<<<<<<<<<<<<<<<<<<<<<<

In [ ]:
filename='nbadraft.json'
if filename:
    with open(filename,'r') as f:
        datastore=json.load(f)

In [ ]:
dat=datastore['resultSets'][0]['rowSet']
cols=datastore['resultSets'][0]['headers']
draftdat=pd.DataFrame(dat,columns=cols)
draftdat.info()

In [ ]:
draftdat.head()

In [ ]:
draftdat.SEASON=pd.to_numeric(draftdat.SEASON)
lotdat=draftdat[(draftdat.SEASON>=1985)&(draftdat.ROUND_NUMBER<=2)]

In [ ]:
lotdat.tail()

In [ ]:
lotdat['Draft_Year']=lotdat['SEASON']
lotdat['EXPERIENCE']=0
lotdat.tail()

In [ ]:
lotdat2=pd.DataFrame()

for i in range(5):
    lotdatadd=lotdat.copy(deep=True)
    inc=1+i
    lotdatadd['SEASON']=lotdatadd['SEASON']+inc
    lotdatadd['EXPERIENCE']=lotdatadd['EXPERIENCE']+inc
    lotdat2=lotdat2.append(lotdatadd)
lotdat2=lotdat2[lotdat2.SEASON<2019].sort_values(["Draft_Year","SEASON","OVERALL_PICK"],ascending=[False,True,True])

In [ ]:
lotdat2.tail(100)

In [ ]:
lotdat2.head(100)

In [ ]:
lotdat2.shape